// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmemrmrvnfxbkzhssjdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZW1ybXJ2bmZ4Ymt6aHNzamRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjEyMjgsImV4cCI6MjA2OTI5NzIyOH0.kvkiPHLgOtr8s_kJ4QjoC5NGyHnepUktQfrY00h49Hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});